export const trens = [
  {
    Patio: 'ZBL',
  },
];

export const mapaEstacoesGraoDictionaty = {
  EOO: {
    estacaoPatio: 'EOO',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', '', '', ''],
  },
  EPY: {
    estacaoPatio: 'EPY',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  EBZ: {
    estacaoPatio: 'EBZ',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  EBU: {
    estacaoPatio: 'EBU',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', 'ZBL'],
  },
  EPO: {
    estacaoPatio: 'EPO',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['EVV', 'EGN', 'EYG', 'EYH'],
  },
  EBJ: {
    estacaoPatio: 'EBJ',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  // EAU: {
  //   estacaoPatio: 'EAU',
  //   marco: true,
  //   carregamento: false,
  //   descarregamento: false,
  //   proximos: ['ZPR', 'ZHF', 'ZUL', 'ZHU', 'ZYE'],
  // }
  ZZB: {
    estacaoPatio: 'ZZB',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['ZNI', 'ZDW', 'ZKJ', 'ZMN'],
  },
  ZUB: {
    estacaoPatio: 'ZUB',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: [
      'ZOQ',
      'ZVF',
      'ZWA',
      'ZBC',
      'ZYW',
      'ZGU',
      'ZG2',
      'ZPE',
      'ZHB',
      'ZKR',
      'ZJN',
    ],
  },
  ZRP: {
    estacaoPatio: 'ZRP',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: [
      'ZEG',
      'ZEK',
      'ZCE',
      'ZHI',
      'ZHM',
      'ZTD',
      'ZCB',
      'ZLB',
      'ZAI',
      'ZMQ',
      'ZEA',
      'ZMG',
      'ZMM',
      'ZXD',
      'ZJJ',
      'ZZZ',
      'ZZQ',
    ],
  },
  ZOP: {
    estacaoPatio: 'ZOP',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  ZBL: {
    estacaoPatio: 'ZBL',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: [
      'ZQB',
      'ZDS',
      'ZVK',
      'ZIC',
      'ZXI',
      'ZST',
      'ZYU',
      'ZFY',
      'ZXP',
      'ZDY',
      'ZDI',
      'ZER',
      'ZCX',
      'ZXY',
      'ZPS',
    ],
  },
  ZKE: {
    estacaoPatio: 'ZKE',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: [
      'ZWW',
      'ZKW',
      'ZLU',
      'ZWI',
      'ZYQ',
      'ZEM',
      'ZMS',
      'ZEJ',
      'ZRB',
      'ZEV',
      'ZEZ',
      'ZXW',
      '95',
      'ZGP',
      'ZWU',
    ],
  },
  ZPT: {
    estacaoPatio: 'ZPT',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  ZGM: {
    estacaoPatio: 'ZGM',
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  ZPG: {
    estacaoPatio: 'ZPG',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  ISN: {
    estacaoPatio: 'ISN',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  IAA: {
    estacaoPatio: 'IAA',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  ICZ: {
    estacaoPatio: 'ICZ',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  IUF: {
    estacaoPatio: 'IUF',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
  IFA: {
    estacaoPatio: 'IFA',
    marco: true,
    carregamento: false,
    descarregamento: false,
    proximos: ['', ''],
  },
};

